name: Build 

on:
    push:

jobs:
    build:
      strategy:
        matrix:
          os: [macos-latest, ubuntu-latest, windows-latest]
          ui: [cui,gui]
  
      runs-on: ${{ matrix.os }}
  
      steps:
        - name: Check-out repository
          uses: actions/checkout@v3
  
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11' # Version range or exact version of a Python version to use, using SemVer's version range syntax

        - name: Build cui
          uses: Nuitka/Nuitka-Action@main
          if: ${{ matrix.ui == 'cui' }}
          with:
            nuitka-version: main
            script-name: KindleUnpack.py
            onefile: true
            standalone: true
            output-file: kindleunpack-${{ matrix.os }}-cui
        
        - name: Build gui
          if: ${{ matrix.ui == 'gui' }}
          uses: Nuitka/Nuitka-Action@main
          with:
            nuitka-version: main
            script-name: KindleUnpack.pyw
            onefile: true
            standalone: true
            enable-plugins: tk-inter
            output-file: kindleunpack-${{ matrix.os }}-gui
  
        - name: Upload Artifacts
          uses: actions/upload-artifact@v3
          with:
            name: ${{ runner.os }} Build
            path: |
              build/*.exe
              build/kindleunpack-${{ matrix.os }}-gui
              build/kindleunpack-${{ matrix.os }}-cui
      
        - name: check build
          if: ${{matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'}}
          run: |
            ls -l build

        - name: Tag the repository
          id: tag
          run: |
              # See https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names
              TAG=v$(date -Iseconds | sed 's/[T:\+]/-/g')
              echo "$TAG"
              echo "tag=$TAG" >> $GITHUB_OUTPUT
              git config user.name "GitHub Action"
              git config user.email "bloop@blorp.com"
              git tag -a $TAG -m "Published version $TAG" ${GITHUB_SHA}
              git push origin $TAG
         
        - name: Cut a new release
          uses: softprops/action-gh-release@v1
          with:
            tag_name: ${{ steps.tag.outputs.tag }}
            files: |
              build/*.exe
              build/kindleunpack-${{ matrix.os }}-gui
              build/kindleunpack-${{ matrix.os }}-cui
      